# Generated by Django 4.1 on 2022-08-08 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('checking_id', models.AutoField(primary_key=True, serialize=False)),
                ('checking_balance', models.BigIntegerField()),
                ('date_balance', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            managers=[
                ('my_checking', django.db.models.manager.Manager()),
            ],
        ),
    ]
