# Generated by Django 4.1 on 2022-08-16 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Checking', '0002_alter_checking_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingUpdate',
            fields=[
                ('checking_id', models.AutoField(primary_key=True, serialize=False)),
                ('checking_balance', models.BigIntegerField()),
                ('date_balance', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('my_checking', django.db.models.manager.Manager()),
            ],
        ),
    ]
