# Generated by Django 4.1 on 2022-11-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=3),
        ),
    ]
